### ISSUE TITLE
Suggestion: metric based on implicit loading of feature bundles

### ISSUE THREAD

**Issue by djzort** [karenetheridge/Test-Kwalitee#11]
In light of perl 7 potentially requiring a "use vX.Y", i suggest a new metric based upon an implicit loading of a feature bundle, and perhaps a lower value metric for explicitly loading a feature bundle.

For reference of readers (im 100% certain karen knows what they are), see also https://perldoc.perl.org/feature.html

It seems "use warnings" isnt a metric either, just use strict, so perhaps that deserves a metric?

**Comment by karenetheridge** [comment]
I'm not sure what the metric would warn about? How do we know the user's intent, or that they forgot anything?

In any case:
- 'use warnings' is indeed an available kwalitee metric (it's enabled by Test::Kwalitee::Extra), and
- metrics are actually provided via Module::CPANTS::Analyse (TK is just a front end using the test infrastructure), so new metric suggestions belong in its issue queue, https://rt.cpan.org/Public/Dist/Display.html?Name=Module-CPANTS-Analyse.
